version: '2.3'
services:
  test:
    build:
      context: .
      args:
        MY_USER: ${MY_USER:-root}
    volumes:
    - ${MY_WORKSPACE}:/ws
    working_dir: /ws${WORKSPACE_PATH:-/}
    user: ${MY_USER:-root}
    command: >
      sh -c "echo "sdk.dir=/usr/local/android-sdk" > local.properties &&
              ./gradlew incrementVersionCode &&
             ./gradlew sendReleaseCandidateUserToCrashlytics"